config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'flats#index'
  resources :flats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_flat
    @flat = Flat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>">
  <p>
    <strong>Name:</strong>
    <%= flat.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= flat.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= flat.description %>
  </p>

  <p>
    <strong>Price per night:</strong>
    <%= flat.price_per_night %>
  </p>

  <p>
    <strong>Number of guests:</strong>
    <%= flat.number_of_guests %>
  </p>

</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">Editing flat</h1>
      <%= render "form", flat: @flat %>
      <div class="d-flex justify-content-center mt-3">
        <%= link_to "Show this flat", @flat, class: "btn btn-primary me-2" %> |
        <%= link_to "Back to flats", flats_path, class: "btn btn-secondary ms-2" %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<!-- app/views/flats/index.html.erb -->

<p style="color: green"><%= notice %></p>

<h1>Flats</h1>

<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4">
        <div class="card mb-4">
          <img src="https://via.placeholder.com/300x200.png?text=No+Image" class="card-img-top" alt="<%= flat.name %>">
          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <p><strong><%= number_to_currency(flat.price_per_night) %></strong> per night</p>
            <a href="<%= flat_path(flat) %>" class="btn btn-primary">More Info</a>
            <a href="<%= edit_flat_path(flat) %>" class="btn btn-secondary">Edit</a>
            <%= link_to "Remove", flat_path(flat), data: { turbo_method: "delete", turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">New flat</h1>
      <%= render "form", flat: @flat %>
      <div class="d-flex justify-content-center mt-3">
        <%= link_to "Back to flats", flats_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<!-- app/views/flats/show.html.erb -->

<p style="color: green"><%= notice %></p>

<div class="position-relative">
  <img src="https://via.placeholder.com/300x200.png?text=No+Image" class="card-img-top img-fluid max-width: 10%" alt="<%= @flat.name %>">
  <div class="position-absolute top-50 start-50 translate-middle text-center text-white">
    <h1><%= @flat.name %></h1>
    <p><%= @flat.address %></p>
  </div>
</div>

<div class="container my-4">
  <div class="row">
    <div class="col-md-8">
      <h2>A bit more on this flat:</h2>
      <p><%= @flat.description %></p>
      <img src="https://via.placeholder.com/500x300" class="img-fluid w-100 my-4" alt="Map">
    </div>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Book this place</h5>
          <form>
            <div class="mb-3">
              <label for="fromDate" class="form-label">From</label>
              <input type="date" class="form-control" id="fromDate">
            </div>
            <div class="mb-3">
              <label for="toDate" class="form-label">To</label>
              <input type="date" class="form-control" id="toDate">
            </div>
            <p><strong><%= number_to_currency(@flat.price_per_night) %></strong> per night</p>
            <button type="submit" class="btn btn-primary">Book</button>
          </form>
        </div>
      </div>
      <button type="button" class="btn btn-link">Share</button>
    </div>
  </div>
</div>

app/views/flatts/_flatt.html.erb
<div id="<%= dom_id flatt %>">
  <p>
    <strong>Name:</strong>
    <%= flatt.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= flatt.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= flatt.description %>
  </p>

  <p>
    <strong>Price per night:</strong>
    <%= flatt.price_per_night %>
  </p>

  <p>
    <strong>Number of guests:</strong>
    <%= flatt.number_of_guests %>
  </p>

</div>

app/views/flatts/_form.html.erb
<%= simple_form_for(@flatt) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Simple Airbnb", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="d-flex" action="<%= flats_path %>" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <%= link_to "Add Flat", new_flat_path, class: "btn btn-primary ms-auto" %>
    </div>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>
</html>